import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ModeToggle } from '@/components/modeToggle'
import dynamic from 'next/dynamic'

// Resolve hydration warning of using attribute "class" and "style" that caused by the difference between React tree rendering
const ThemeProvider = dynamic(() => import('@/components/theme-provider'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <div id="root" className="h-screen w-screen overflow-hidden p-1">
                        <div className="overflow-hidden h-full w-full p-1">
                            { children }
                        </div>
                        <ModeToggle />
                    </div>
                </ThemeProvider>
            </body>
        </html>
    )
}
